# Generated by Django 4.0.2 on 2022-02-10 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('JD', 'Judo'), ('MM', 'MMA'), ('BX', 'Box')], default=None, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EasyChampUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('JG', 'Judge'), ('OG', 'Organization'), ('SP', 'Sportsman'), ('CH', 'Coach'), ('EA', 'Event Admin')], default=None, max_length=2)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='easychamp.clubs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clubs',
            name='sport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='easychamp.sport'),
        ),
    ]
