# Generated by Django 4.0.2 on 2022-02-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easychamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='nameId',
            field=models.CharField(choices=[('JD', 'Judo'), ('MM', 'MMA'), ('BX', 'Box')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
