# Generated by Django 4.0.2 on 2022-02-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easychamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easychamp.sport'),
        ),
    ]
