# Generated by Django 4.0.2 on 2022-02-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easychamp', '0002_sport_nameid_alter_sport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
