export const GET_CLUBS_REQUST = "GET_CLUBS_REQUST"
export const GET_CLUBS_SUCCESS = "GET_CLUBS_SUCCESS"
export const GET_CLUBS_FAIL = "GET_CLUBS_FAIL"
export const GET_CLUBS_RESET = "GET_CLUBS_RESET"
